name = "MathML"
uuid = "abcecc63-2b08-419c-80c4-c63dca6fa478"
version = "0.1.18"
authors = ["anand <anandj@uchicago.edu> and contributors"]

[deps]
AbstractTrees = "1520ce14-60c1-5f80-bbc7-55ef81b5835c"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
EzXML = "8f5d6c58-4d21-5cfd-889c-e3ad7ee6a615"
IfElse = "615f187c-cbe4-4ef1-ba3b-2fcf58d6d173"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Symbolics = "0c5d862f-8b57-4792-8d23-62f2024744c7"

[compat]
AbstractTrees = "0.4"
DocStringExtensions = "0.9"
EzXML = "1"
IfElse = "0.1"
PrecompileTools = "1"
SpecialFunctions = "2"
Statistics = "1.11.1"
Symbolics = "6, 7.4"
julia = "1.10"
[extras]
ModelingToolkit = "961ee093-0014-501f-94e3-6117800e7a78"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "ModelingToolkit"]
